blank_issues_enabled: true
contact_links:
  - name: Discord community
    url: https://discord.gg/wHX6j7wG5d
    about: 'Join our Discord community'
  - name: Slack community
    url: https://join.slack.com/t/thekindecommunity/shared_invite/zt-2k5i0aeet-d6Z_2qYphcNCpj0bFa4oCg
    about: 'Join our Slack community'
