// DO NOT EDIT THIS FILE - This reads the `sidebarData.ts` file and
// removes extra data not used in the `sidebar` entry in `astro.config.mjs`

import sidebarData from "./sidebarData";

const transformSidebarData = (data: any) => {
  return data.map((item: any) => {
    const {icon, description, ...rest} = item;
    const transformedItem = {
      ...rest,
      items: item.items
        ? item.items.map((subItem: any) => {
            const {icon, description, ...subRest} = subItem;
            return subRest;
          })
        : []
    };
    return transformedItem;
  });
};

const sidebarConfig = transformSidebarData(sidebarData);

export default sidebarConfig;
